In [1]:
!python --version

Python 3.10.18

In [2]:
import json
import random
import os

os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"
os.environ["VLLM_LOGGING_LEVEL"] = "ERROR"

from datasets import load_dataset
from langchain_community.llms import VLLM
from langchain_huggingface import HuggingFaceEmbeddings
import numpy as np
import pandas as pd
import torch
from transformers import AutoTokenizer

from rag_bench import baseline, data, evaluator, results

In [3]:
HIST_PRIVATE_QA_REPO_ID: str = "ai-forever/hist-rag-bench-private-qa"
HIST_PRIVATE_TEXTS_REPO_ID: str = "ai-forever/hist-rag-bench-private-texts"
RANDOM_SEED: int = 42
EMBEDDER_NAME: str = "ai-forever/FRIDA"
LLM_NAME: str = "bond005/meno-tiny-0.1"

In [4]:
LLM_PROMPT: str = """Проанализируйте заданный контекст и ответьте на вопрос пользователя на основе сведений, предоставленных в этом контексте.
Не давайте никаких объяснений и пояснений к своему ответу. Не пишите ничего лишнего. Не извиняйтесь, не стройте диалог. Выдавайте только ответ и ничего больше.
Отвечайте на русском языке.
Если в заданном контексте нет информации для ответа на вопрос пользователя, то ничего не придумывайте и просто откажитесь отвечать.
"""
print(LLM_PROMPT)

Проанализируйте заданный контекст и ответьте на вопрос пользователя на основе сведений, предоставленных в этом контексте.
Не давайте никаких объяснений и пояснений к своему ответу. Не пишите ничего лишнего. Не извиняйтесь, не стройте диалог. Выдавайте только ответ и ничего больше.
Отвечайте на русском языке.
Если в заданном контексте нет информации для ответа на вопрос пользователя, то ничего не придумывайте и просто откажитесь отвечать.

In [5]:
def get_private_qa_dataset(version):
    return load_dataset(HIST_PRIVATE_QA_REPO_ID, revision=version)


def get_private_texts_dataset(version):
    return load_dataset(HIST_PRIVATE_TEXTS_REPO_ID, revision=version)


def get_public_to_private_texts_mapping(version):
    private_texts_ds = get_private_texts_dataset(version)
    mapping = {}
    for item in private_texts_ds["train"]:
        mapping[item["public_id"]] = item["id"]
    return mapping

In [6]:
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
torch.random.manual_seed(RANDOM_SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(RANDOM_SEED)

In [7]:
#get public datasets (history ones)
texts_ds, questions_ds, version = data.get_datasets(is_hist=True)
print(f"version = {version}")

Latest texts version: 1.13.0
Latest questions version: 1.13.0
Loaded texts dataset with 560 texts
Loaded questions dataset with 600 questions
version = 1.13.0

In [8]:
#get private datasets (history ones)
qa_dataset = get_private_qa_dataset(version)
mapping = get_public_to_private_texts_mapping(version)

In [9]:
llm = VLLM(
    model=LLM_NAME,
    tensor_parallel_size=1,
    max_new_tokens=256,
    top_p=0.95,
    temperature=0.3,
    vllm_kwargs={
        "gpu_memory_utilization": 0.45,
        "max_num_batched_tokens": 8192,
        "max_model_len": 4096,
        "disable_log_stats": True,
        "seed": RANDOM_SEED
    }
)
tok = AutoTokenizer.from_pretrained(LLM_NAME)

[W114 17:13:45.400549202 ProcessGroupNCCL.cpp:981] Warning: TORCH_NCCL_AVOID_RECORD_STREAMS is the default now, this environment variable is thus deprecated. (function operator())

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.32it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.32it/s]
(EngineCore_DP0 pid=41758)
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:03<00:00, 20.93it/s]

In [10]:
embedding_model = HuggingFaceEmbeddings(
    model_name="ai-forever/FRIDA",
    model_kwargs={"trust_remote_code": True},
    encode_kwargs={"batch_size": 16, "prompt": "search_document: "},
    query_encode_kwargs={"prompt": "search_query: "}
)

In [11]:
retrieval = baseline.init_retriever(
    texts_ds,
    embedding_model,
    top_k=5,
    chunk_size=500,
    chunk_overlap=100,
)
generation = baseline.init_generation(retrieval, llm, tok, system_prompt=LLM_PROMPT)

Initializing retriever
> Creating vector store
> Vector store created for 560 documents
> Done for 57.21 seconds
Initializing generation chain
> Done

In [12]:
res = baseline.get_results(
    generation, questions_ds, write_logs=False
)

Calculating and preparing results

  0%|                                                                                                                | 0/600 [00:00<?, ?it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  0%|▏                                                                                                       | 1/600 [00:00<04:03,  2.46it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  0%|▎                                                                                                       | 2/600 [00:00<02:43,  3.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  0%|▌                                                                                                       | 3/600 [00:00<02:13,  4.46it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  1%|▋                                                                                                       | 4/600 [00:01<02:43,  3.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  1%|▊                                                                                                       | 5/600 [00:01<02:20,  4.25it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  1%|█                                                                                                       | 6/600 [00:02<04:43,  2.09it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  1%|█▏                                                                                                      | 7/600 [00:02<04:00,  2.47it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  1%|█▍                                                                                                      | 8/600 [00:02<04:08,  2.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  2%|█▌                                                                                                      | 9/600 [00:03<03:23,  2.90it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  2%|█▋                                                                                                     | 10/600 [00:03<03:05,  3.19it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  2%|█▉                                                                                                     | 11/600 [00:03<02:39,  3.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  2%|██                                                                                                     | 12/600 [00:03<02:20,  4.19it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  2%|██▏                                                                                                    | 13/600 [00:03<02:13,  4.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  2%|██▍                                                                                                    | 14/600 [00:04<02:11,  4.47it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  2%|██▌                                                                                                    | 15/600 [00:04<03:20,  2.91it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  3%|██▋                                                                                                    | 16/600 [00:04<03:01,  3.22it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  3%|██▉                                                                                                    | 17/600 [00:05<03:40,  2.64it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  3%|███                                                                                                    | 18/600 [00:06<05:12,  1.86it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  3%|███▎                                                                                                   | 19/600 [00:08<08:33,  1.13it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  3%|███▍                                                                                                   | 20/600 [00:08<07:25,  1.30it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  4%|███▌                                                                                                   | 21/600 [00:08<05:50,  1.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  4%|███▊                                                                                                   | 22/600 [00:09<04:54,  1.96it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  4%|███▉                                                                                                   | 23/600 [00:09<04:47,  2.01it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  4%|████                                                                                                   | 24/600 [00:09<04:21,  2.21it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  4%|████▎                                                                                                  | 25/600 [00:10<03:50,  2.49it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  4%|████▍                                                                                                  | 26/600 [00:10<03:11,  3.00it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  4%|████▋                                                                                                  | 27/600 [00:10<02:42,  3.52it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  5%|████▊                                                                                                  | 28/600 [00:10<02:33,  3.73it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  5%|████▉                                                                                                  | 29/600 [00:10<02:10,  4.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  5%|█████▏                                                                                                 | 30/600 [00:11<02:27,  3.86it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  5%|█████▎                                                                                                 | 31/600 [00:11<02:15,  4.21it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  5%|█████▍                                                                                                 | 32/600 [00:11<02:16,  4.15it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  6%|█████▋                                                                                                 | 33/600 [00:11<02:13,  4.26it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  6%|█████▊                                                                                                 | 34/600 [00:12<02:03,  4.59it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  6%|██████                                                                                                 | 35/600 [00:12<01:56,  4.87it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  6%|██████▏                                                                                                | 36/600 [00:12<01:47,  5.27it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  6%|██████▎                                                                                                | 37/600 [00:12<02:07,  4.40it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  6%|██████▌                                                                                                | 38/600 [00:13<02:54,  3.22it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  6%|██████▋                                                                                                | 39/600 [00:13<02:29,  3.75it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  7%|██████▊                                                                                                | 40/600 [00:13<02:33,  3.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  7%|███████                                                                                                | 41/600 [00:13<02:18,  4.05it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  7%|███████▏                                                                                               | 42/600 [00:14<02:08,  4.34it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  7%|███████▍                                                                                               | 43/600 [00:14<02:32,  3.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  7%|███████▌                                                                                               | 44/600 [00:14<02:33,  3.62it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  8%|███████▋                                                                                               | 45/600 [00:14<02:31,  3.66it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  8%|███████▉                                                                                               | 46/600 [00:15<02:13,  4.15it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  8%|████████                                                                                               | 47/600 [00:15<02:15,  4.07it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  8%|████████▏                                                                                              | 48/600 [00:15<02:06,  4.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  8%|████████▍                                                                                              | 49/600 [00:15<02:04,  4.44it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  8%|████████▌                                                                                              | 50/600 [00:16<02:29,  3.68it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  8%|████████▊                                                                                              | 51/600 [00:16<03:50,  2.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  9%|████████▉                                                                                              | 52/600 [00:17<03:13,  2.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  9%|█████████                                                                                              | 53/600 [00:17<02:52,  3.17it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  9%|█████████▎                                                                                             | 54/600 [00:17<02:43,  3.33it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  9%|█████████▍                                                                                             | 55/600 [00:17<02:40,  3.39it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

  9%|█████████▌                                                                                             | 56/600 [00:18<02:32,  3.57it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 10%|█████████▊                                                                                             | 57/600 [00:18<02:34,  3.52it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 10%|█████████▉                                                                                             | 58/600 [00:18<02:16,  3.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 10%|██████████▏                                                                                            | 59/600 [00:18<02:13,  4.05it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 10%|██████████▎                                                                                            | 60/600 [00:19<02:03,  4.39it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 10%|██████████▍                                                                                            | 61/600 [00:19<01:57,  4.57it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 10%|██████████▋                                                                                            | 62/600 [00:19<02:04,  4.32it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 10%|██████████▊                                                                                            | 63/600 [00:19<02:00,  4.45it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 11%|██████████▉                                                                                            | 64/600 [00:19<01:46,  5.04it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 11%|███████████▏                                                                                           | 65/600 [00:20<01:45,  5.06it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 11%|███████████▎                                                                                           | 66/600 [00:20<02:02,  4.35it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 11%|███████████▌                                                                                           | 67/600 [00:20<02:34,  3.44it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 11%|███████████▋                                                                                           | 68/600 [00:20<02:10,  4.09it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 12%|███████████▊                                                                                           | 69/600 [00:21<02:13,  3.99it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 12%|████████████                                                                                           | 70/600 [00:21<02:18,  3.82it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 12%|████████████▏                                                                                          | 71/600 [00:21<02:26,  3.61it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 12%|████████████▎                                                                                          | 72/600 [00:21<02:12,  4.00it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 12%|████████████▌                                                                                          | 73/600 [00:22<02:19,  3.77it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 12%|████████████▋                                                                                          | 74/600 [00:22<02:16,  3.85it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 12%|████████████▉                                                                                          | 75/600 [00:22<02:12,  3.96it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 13%|█████████████                                                                                          | 76/600 [00:23<02:22,  3.67it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 13%|█████████████▏                                                                                         | 77/600 [00:23<03:08,  2.78it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 13%|█████████████▍                                                                                         | 78/600 [00:23<02:40,  3.26it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 13%|█████████████▌                                                                                         | 79/600 [00:24<02:28,  3.50it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 13%|█████████████▋                                                                                         | 80/600 [00:24<02:15,  3.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 14%|█████████████▉                                                                                         | 81/600 [00:24<02:10,  3.98it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 14%|██████████████                                                                                         | 82/600 [00:24<02:03,  4.19it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 14%|██████████████▏                                                                                        | 83/600 [00:24<02:00,  4.28it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 14%|██████████████▍                                                                                        | 84/600 [00:25<01:49,  4.69it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 14%|██████████████▌                                                                                        | 85/600 [00:25<01:44,  4.94it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 14%|██████████████▊                                                                                        | 86/600 [00:25<01:47,  4.77it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 14%|██████████████▉                                                                                        | 87/600 [00:25<01:42,  5.01it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 15%|███████████████                                                                                        | 88/600 [00:25<01:42,  4.98it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 15%|███████████████▎                                                                                       | 89/600 [00:26<01:39,  5.13it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 15%|███████████████▍                                                                                       | 90/600 [00:26<02:10,  3.92it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 15%|███████████████▌                                                                                       | 91/600 [00:26<01:58,  4.31it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 15%|███████████████▊                                                                                       | 92/600 [00:26<01:48,  4.67it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 16%|███████████████▉                                                                                       | 93/600 [00:27<01:49,  4.61it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 16%|████████████████▏                                                                                      | 94/600 [00:27<02:14,  3.76it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 16%|████████████████▎                                                                                      | 95/600 [00:27<02:18,  3.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 16%|████████████████▍                                                                                      | 96/600 [00:27<02:00,  4.17it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 16%|████████████████▋                                                                                      | 97/600 [00:28<01:47,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 16%|████████████████▊                                                                                      | 98/600 [00:28<01:42,  4.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 16%|████████████████▉                                                                                      | 99/600 [00:28<01:39,  5.04it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 17%|█████████████████                                                                                     | 100/600 [00:28<01:44,  4.80it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 17%|█████████████████▏                                                                                    | 101/600 [00:28<01:46,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 17%|█████████████████▎                                                                                    | 102/600 [00:29<01:41,  4.92it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 17%|█████████████████▌                                                                                    | 103/600 [00:29<01:40,  4.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 17%|█████████████████▋                                                                                    | 104/600 [00:29<01:50,  4.48it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 18%|█████████████████▊                                                                                    | 105/600 [00:29<01:47,  4.62it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 18%|██████████████████                                                                                    | 106/600 [00:29<01:54,  4.32it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 18%|██████████████████▏                                                                                   | 107/600 [00:30<01:47,  4.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 18%|██████████████████▎                                                                                   | 108/600 [00:30<01:47,  4.58it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 18%|██████████████████▌                                                                                   | 109/600 [00:30<02:18,  3.55it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 18%|██████████████████▋                                                                                   | 110/600 [00:31<02:09,  3.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 18%|██████████████████▊                                                                                   | 111/600 [00:31<01:54,  4.25it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 19%|███████████████████                                                                                   | 112/600 [00:31<01:45,  4.62it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 19%|███████████████████▏                                                                                  | 113/600 [00:31<01:46,  4.57it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 19%|███████████████████▍                                                                                  | 114/600 [00:31<01:48,  4.47it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 19%|███████████████████▌                                                                                  | 115/600 [00:32<02:36,  3.09it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 19%|███████████████████▋                                                                                  | 116/600 [00:32<02:13,  3.63it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 20%|███████████████████▉                                                                                  | 117/600 [00:32<02:03,  3.92it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 20%|████████████████████                                                                                  | 118/600 [00:32<01:51,  4.31it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 20%|████████████████████▏                                                                                 | 119/600 [00:33<01:43,  4.64it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 20%|████████████████████▍                                                                                 | 120/600 [00:33<01:50,  4.36it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 20%|████████████████████▌                                                                                 | 121/600 [00:33<01:55,  4.15it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 20%|████████████████████▋                                                                                 | 122/600 [00:33<01:55,  4.13it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 20%|████████████████████▉                                                                                 | 123/600 [00:34<01:57,  4.07it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 21%|█████████████████████                                                                                 | 124/600 [00:34<01:53,  4.21it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 21%|█████████████████████▎                                                                                | 125/600 [00:34<02:20,  3.37it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 21%|█████████████████████▍                                                                                | 126/600 [00:34<02:06,  3.75it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 21%|█████████████████████▌                                                                                | 127/600 [00:35<02:22,  3.31it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 21%|█████████████████████▊                                                                                | 128/600 [00:35<02:04,  3.78it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 22%|█████████████████████▉                                                                                | 129/600 [00:35<01:58,  3.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 22%|██████████████████████                                                                                | 130/600 [00:35<01:52,  4.18it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 22%|██████████████████████▎                                                                               | 131/600 [00:36<01:54,  4.09it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 22%|██████████████████████▍                                                                               | 132/600 [00:36<02:01,  3.86it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 22%|██████████████████████▌                                                                               | 133/600 [00:36<01:52,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 22%|██████████████████████▊                                                                               | 134/600 [00:36<01:51,  4.20it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 22%|██████████████████████▉                                                                               | 135/600 [00:37<01:46,  4.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 23%|███████████████████████                                                                               | 136/600 [00:37<01:39,  4.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 23%|███████████████████████▎                                                                              | 137/600 [00:37<01:48,  4.26it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 23%|███████████████████████▍                                                                              | 138/600 [00:37<01:43,  4.45it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 23%|███████████████████████▋                                                                              | 139/600 [00:38<01:43,  4.44it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 23%|███████████████████████▊                                                                              | 140/600 [00:38<01:49,  4.20it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 24%|███████████████████████▉                                                                              | 141/600 [00:38<01:46,  4.29it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 24%|████████████████████████▏                                                                             | 142/600 [00:38<01:42,  4.49it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 24%|████████████████████████▎                                                                             | 143/600 [00:38<01:39,  4.58it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 24%|████████████████████████▍                                                                             | 144/600 [00:39<01:42,  4.43it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 24%|████████████████████████▋                                                                             | 145/600 [00:39<01:37,  4.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 24%|████████████████████████▊                                                                             | 146/600 [00:39<01:38,  4.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 24%|████████████████████████▉                                                                             | 147/600 [00:39<01:31,  4.93it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 25%|█████████████████████████▏                                                                            | 148/600 [00:39<01:33,  4.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 25%|█████████████████████████▎                                                                            | 149/600 [00:40<01:28,  5.12it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 25%|█████████████████████████▌                                                                            | 150/600 [00:40<01:37,  4.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 25%|█████████████████████████▋                                                                            | 151/600 [00:40<01:35,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 25%|█████████████████████████▊                                                                            | 152/600 [00:40<01:47,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 26%|██████████████████████████                                                                            | 153/600 [00:41<01:41,  4.40it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 26%|██████████████████████████▏                                                                           | 154/600 [00:41<02:14,  3.32it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 26%|██████████████████████████▎                                                                           | 155/600 [00:41<02:03,  3.61it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 26%|██████████████████████████▌                                                                           | 156/600 [00:42<01:54,  3.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 26%|██████████████████████████▋                                                                           | 157/600 [00:42<01:43,  4.29it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 26%|██████████████████████████▊                                                                           | 158/600 [00:42<02:14,  3.29it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 26%|███████████████████████████                                                                           | 159/600 [00:42<01:56,  3.78it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 27%|███████████████████████████▏                                                                          | 160/600 [00:43<01:56,  3.78it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 27%|███████████████████████████▎                                                                          | 161/600 [00:43<01:45,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 27%|███████████████████████████▌                                                                          | 162/600 [00:43<01:44,  4.17it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 27%|███████████████████████████▋                                                                          | 163/600 [00:43<01:39,  4.41it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 27%|███████████████████████████▉                                                                          | 164/600 [00:43<01:36,  4.50it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 28%|████████████████████████████                                                                          | 165/600 [00:44<01:30,  4.82it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 28%|████████████████████████████▏                                                                         | 166/600 [00:44<01:27,  4.98it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 28%|████████████████████████████▍                                                                         | 167/600 [00:44<01:26,  4.99it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 28%|████████████████████████████▌                                                                         | 168/600 [00:44<01:28,  4.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 28%|████████████████████████████▋                                                                         | 169/600 [00:44<01:26,  4.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 28%|████████████████████████████▉                                                                         | 170/600 [00:45<01:28,  4.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 28%|█████████████████████████████                                                                         | 171/600 [00:45<01:32,  4.66it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 29%|█████████████████████████████▏                                                                        | 172/600 [00:45<01:36,  4.45it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 29%|█████████████████████████████▍                                                                        | 173/600 [00:45<01:30,  4.74it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 29%|█████████████████████████████▌                                                                        | 174/600 [00:46<02:13,  3.18it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 29%|█████████████████████████████▊                                                                        | 175/600 [00:46<02:18,  3.08it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 29%|█████████████████████████████▉                                                                        | 176/600 [00:46<01:57,  3.62it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 30%|██████████████████████████████                                                                        | 177/600 [00:47<02:12,  3.20it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 30%|██████████████████████████████▎                                                                       | 178/600 [00:47<01:59,  3.54it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 30%|██████████████████████████████▍                                                                       | 179/600 [00:47<01:53,  3.71it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 30%|██████████████████████████████▌                                                                       | 180/600 [00:47<01:40,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 30%|██████████████████████████████▊                                                                       | 181/600 [00:48<01:52,  3.71it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 30%|██████████████████████████████▉                                                                       | 182/600 [00:48<01:40,  4.15it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 30%|███████████████████████████████                                                                       | 183/600 [00:48<01:33,  4.45it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 31%|███████████████████████████████▎                                                                      | 184/600 [00:48<01:30,  4.62it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 31%|███████████████████████████████▍                                                                      | 185/600 [00:49<01:52,  3.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 31%|███████████████████████████████▌                                                                      | 186/600 [00:49<01:47,  3.85it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 31%|███████████████████████████████▊                                                                      | 187/600 [00:49<01:42,  4.02it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 31%|███████████████████████████████▉                                                                      | 188/600 [00:49<01:39,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 32%|████████████████████████████████▏                                                                     | 189/600 [00:50<01:38,  4.19it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 32%|████████████████████████████████▎                                                                     | 190/600 [00:50<01:34,  4.34it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 32%|████████████████████████████████▍                                                                     | 191/600 [00:51<02:35,  2.63it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 32%|████████████████████████████████▋                                                                     | 192/600 [00:51<02:31,  2.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 32%|████████████████████████████████▊                                                                     | 193/600 [00:51<02:14,  3.03it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 32%|████████████████████████████████▉                                                                     | 194/600 [00:51<02:00,  3.37it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 32%|█████████████████████████████████▏                                                                    | 195/600 [00:52<01:44,  3.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 33%|█████████████████████████████████▎                                                                    | 196/600 [00:52<01:41,  3.98it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 33%|█████████████████████████████████▍                                                                    | 197/600 [00:52<01:29,  4.53it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 33%|█████████████████████████████████▋                                                                    | 198/600 [00:52<01:31,  4.39it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 33%|█████████████████████████████████▊                                                                    | 199/600 [00:52<01:28,  4.51it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 33%|██████████████████████████████████                                                                    | 200/600 [00:53<01:25,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 34%|██████████████████████████████████▏                                                                   | 201/600 [00:53<01:25,  4.64it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 34%|██████████████████████████████████▎                                                                   | 202/600 [00:53<01:25,  4.68it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 34%|██████████████████████████████████▌                                                                   | 203/600 [00:53<01:23,  4.78it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 34%|██████████████████████████████████▋                                                                   | 204/600 [00:54<01:45,  3.75it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 34%|██████████████████████████████████▊                                                                   | 205/600 [00:54<01:53,  3.48it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 34%|███████████████████████████████████                                                                   | 206/600 [00:54<01:44,  3.78it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 34%|███████████████████████████████████▏                                                                  | 207/600 [00:54<01:36,  4.07it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 35%|███████████████████████████████████▎                                                                  | 208/600 [00:55<01:30,  4.33it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 35%|███████████████████████████████████▌                                                                  | 209/600 [00:55<01:46,  3.66it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 35%|███████████████████████████████████▋                                                                  | 210/600 [00:55<01:40,  3.90it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 35%|███████████████████████████████████▊                                                                  | 211/600 [00:55<01:40,  3.85it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 35%|████████████████████████████████████                                                                  | 212/600 [00:56<02:19,  2.77it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 36%|████████████████████████████████████▏                                                                 | 213/600 [00:56<02:00,  3.21it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 36%|████████████████████████████████████▍                                                                 | 214/600 [00:56<01:38,  3.91it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 36%|████████████████████████████████████▌                                                                 | 215/600 [00:57<01:48,  3.53it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 36%|████████████████████████████████████▋                                                                 | 216/600 [00:57<01:39,  3.86it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 36%|████████████████████████████████████▉                                                                 | 217/600 [00:57<01:29,  4.28it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 36%|█████████████████████████████████████                                                                 | 218/600 [00:57<01:18,  4.89it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 36%|█████████████████████████████████████▏                                                                | 219/600 [00:57<01:18,  4.83it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 37%|█████████████████████████████████████▍                                                                | 220/600 [00:58<01:14,  5.08it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 37%|█████████████████████████████████████▌                                                                | 221/600 [00:58<01:10,  5.40it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 37%|█████████████████████████████████████▋                                                                | 222/600 [00:58<01:03,  5.98it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 37%|█████████████████████████████████████▉                                                                | 223/600 [00:58<01:03,  5.90it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 37%|██████████████████████████████████████                                                                | 224/600 [00:58<01:02,  5.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 38%|██████████████████████████████████████▎                                                               | 225/600 [00:58<01:07,  5.55it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 38%|██████████████████████████████████████▍                                                               | 226/600 [00:59<01:47,  3.48it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 38%|██████████████████████████████████████▌                                                               | 227/600 [00:59<01:30,  4.12it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 38%|██████████████████████████████████████▊                                                               | 228/600 [01:00<02:46,  2.23it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 38%|██████████████████████████████████████▉                                                               | 229/600 [01:00<02:19,  2.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 38%|███████████████████████████████████████                                                               | 230/600 [01:00<02:10,  2.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 38%|███████████████████████████████████████▎                                                              | 231/600 [01:01<01:55,  3.20it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 39%|███████████████████████████████████████▍                                                              | 232/600 [01:01<01:49,  3.37it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 39%|███████████████████████████████████████▌                                                              | 233/600 [01:01<01:50,  3.31it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 39%|███████████████████████████████████████▊                                                              | 234/600 [01:01<01:36,  3.80it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 39%|███████████████████████████████████████▉                                                              | 235/600 [01:02<01:31,  3.98it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 39%|████████████████████████████████████████                                                              | 236/600 [01:02<01:28,  4.12it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 40%|████████████████████████████████████████▎                                                             | 237/600 [01:02<01:32,  3.94it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 40%|████████████████████████████████████████▍                                                             | 238/600 [01:03<02:19,  2.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 40%|████████████████████████████████████████▋                                                             | 239/600 [01:03<01:53,  3.17it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 40%|████████████████████████████████████████▊                                                             | 240/600 [01:03<01:38,  3.66it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 40%|████████████████████████████████████████▉                                                             | 241/600 [01:03<01:29,  4.01it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 40%|█████████████████████████████████████████▏                                                            | 242/600 [01:04<01:23,  4.30it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 40%|█████████████████████████████████████████▎                                                            | 243/600 [01:04<01:21,  4.39it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 41%|█████████████████████████████████████████▍                                                            | 244/600 [01:04<01:18,  4.53it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 41%|█████████████████████████████████████████▋                                                            | 245/600 [01:04<01:15,  4.73it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 41%|█████████████████████████████████████████▊                                                            | 246/600 [01:04<01:10,  5.00it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 41%|█████████████████████████████████████████▉                                                            | 247/600 [01:05<01:06,  5.33it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 41%|██████████████████████████████████████████▏                                                           | 248/600 [01:05<01:04,  5.48it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 42%|██████████████████████████████████████████▎                                                           | 249/600 [01:05<01:12,  4.87it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 42%|██████████████████████████████████████████▌                                                           | 250/600 [01:05<01:24,  4.12it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 42%|██████████████████████████████████████████▋                                                           | 251/600 [01:06<01:30,  3.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 42%|██████████████████████████████████████████▊                                                           | 252/600 [01:06<01:26,  4.04it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 42%|███████████████████████████████████████████                                                           | 253/600 [01:06<01:23,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 42%|███████████████████████████████████████████▏                                                          | 254/600 [01:06<01:16,  4.54it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 42%|███████████████████████████████████████████▎                                                          | 255/600 [01:06<01:14,  4.62it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 43%|███████████████████████████████████████████▌                                                          | 256/600 [01:07<01:35,  3.62it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 43%|███████████████████████████████████████████▋                                                          | 257/600 [01:07<01:29,  3.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 43%|███████████████████████████████████████████▊                                                          | 258/600 [01:07<01:26,  3.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 43%|████████████████████████████████████████████                                                          | 259/600 [01:07<01:23,  4.06it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 43%|████████████████████████████████████████████▏                                                         | 260/600 [01:08<01:23,  4.07it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 44%|████████████████████████████████████████████▎                                                         | 261/600 [01:08<01:32,  3.66it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 44%|████████████████████████████████████████████▌                                                         | 262/600 [01:08<01:38,  3.44it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 44%|████████████████████████████████████████████▋                                                         | 263/600 [01:09<01:27,  3.86it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 44%|████████████████████████████████████████████▉                                                         | 264/600 [01:09<01:19,  4.22it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 44%|█████████████████████████████████████████████                                                         | 265/600 [01:09<01:27,  3.83it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 44%|█████████████████████████████████████████████▏                                                        | 266/600 [01:09<01:31,  3.64it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 44%|█████████████████████████████████████████████▍                                                        | 267/600 [01:10<01:38,  3.39it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 45%|█████████████████████████████████████████████▌                                                        | 268/600 [01:10<01:28,  3.77it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 45%|█████████████████████████████████████████████▋                                                        | 269/600 [01:10<01:27,  3.80it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 45%|█████████████████████████████████████████████▉                                                        | 270/600 [01:10<01:21,  4.06it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 45%|██████████████████████████████████████████████                                                        | 271/600 [01:11<01:23,  3.93it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 45%|██████████████████████████████████████████████▏                                                       | 272/600 [01:11<01:13,  4.46it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 46%|██████████████████████████████████████████████▍                                                       | 273/600 [01:11<01:20,  4.08it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 46%|██████████████████████████████████████████████▌                                                       | 274/600 [01:11<01:18,  4.17it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 46%|██████████████████████████████████████████████▊                                                       | 275/600 [01:12<01:23,  3.91it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 46%|██████████████████████████████████████████████▉                                                       | 276/600 [01:12<01:14,  4.34it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 46%|███████████████████████████████████████████████                                                       | 277/600 [01:12<01:07,  4.76it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 46%|███████████████████████████████████████████████▎                                                      | 278/600 [01:12<01:08,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 46%|███████████████████████████████████████████████▍                                                      | 279/600 [01:12<01:07,  4.78it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 47%|███████████████████████████████████████████████▌                                                      | 280/600 [01:13<01:06,  4.80it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 47%|███████████████████████████████████████████████▊                                                      | 281/600 [01:13<01:07,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 47%|███████████████████████████████████████████████▉                                                      | 282/600 [01:13<01:07,  4.69it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 47%|████████████████████████████████████████████████                                                      | 283/600 [01:13<01:07,  4.72it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 47%|████████████████████████████████████████████████▎                                                     | 284/600 [01:13<01:03,  5.00it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 48%|████████████████████████████████████████████████▍                                                     | 285/600 [01:14<01:00,  5.18it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 48%|████████████████████████████████████████████████▌                                                     | 286/600 [01:14<01:08,  4.57it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 48%|████████████████████████████████████████████████▊                                                     | 287/600 [01:14<01:08,  4.59it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 48%|████████████████████████████████████████████████▉                                                     | 288/600 [01:14<01:09,  4.50it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 48%|█████████████████████████████████████████████████▏                                                    | 289/600 [01:15<01:10,  4.43it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 48%|█████████████████████████████████████████████████▎                                                    | 290/600 [01:15<01:05,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 48%|█████████████████████████████████████████████████▍                                                    | 291/600 [01:15<01:50,  2.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 49%|█████████████████████████████████████████████████▋                                                    | 292/600 [01:16<01:54,  2.68it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 49%|█████████████████████████████████████████████████▊                                                    | 293/600 [01:16<01:40,  3.05it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 49%|█████████████████████████████████████████████████▉                                                    | 294/600 [01:16<01:19,  3.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 49%|██████████████████████████████████████████████████▏                                                   | 295/600 [01:16<01:20,  3.77it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 49%|██████████████████████████████████████████████████▎                                                   | 296/600 [01:17<01:12,  4.21it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 50%|██████████████████████████████████████████████████▍                                                   | 297/600 [01:17<01:07,  4.49it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 50%|██████████████████████████████████████████████████▋                                                   | 298/600 [01:17<01:08,  4.43it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 50%|██████████████████████████████████████████████████▊                                                   | 299/600 [01:17<01:19,  3.80it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 50%|███████████████████████████████████████████████████                                                   | 300/600 [01:18<01:31,  3.29it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 50%|███████████████████████████████████████████████████▏                                                  | 301/600 [01:18<01:40,  2.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 50%|███████████████████████████████████████████████████▎                                                  | 302/600 [01:18<01:34,  3.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 50%|███████████████████████████████████████████████████▌                                                  | 303/600 [01:19<01:23,  3.56it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 51%|███████████████████████████████████████████████████▋                                                  | 304/600 [01:19<01:17,  3.80it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 51%|███████████████████████████████████████████████████▊                                                  | 305/600 [01:19<01:15,  3.91it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 51%|████████████████████████████████████████████████████                                                  | 306/600 [01:19<01:06,  4.41it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 51%|████████████████████████████████████████████████████▏                                                 | 307/600 [01:20<01:04,  4.52it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 51%|████████████████████████████████████████████████████▎                                                 | 308/600 [01:20<00:59,  4.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 52%|████████████████████████████████████████████████████▌                                                 | 309/600 [01:20<01:00,  4.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 52%|████████████████████████████████████████████████████▋                                                 | 310/600 [01:20<01:14,  3.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 52%|████████████████████████████████████████████████████▊                                                 | 311/600 [01:20<01:09,  4.15it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 52%|█████████████████████████████████████████████████████                                                 | 312/600 [01:21<01:07,  4.26it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 52%|█████████████████████████████████████████████████████▏                                                | 313/600 [01:21<01:03,  4.49it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 52%|█████████████████████████████████████████████████████▍                                                | 314/600 [01:21<00:58,  4.86it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 52%|█████████████████████████████████████████████████████▌                                                | 315/600 [01:21<00:59,  4.76it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 53%|█████████████████████████████████████████████████████▋                                                | 316/600 [01:21<00:56,  5.01it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 53%|█████████████████████████████████████████████████████▉                                                | 317/600 [01:22<01:00,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 53%|██████████████████████████████████████████████████████                                                | 318/600 [01:22<00:55,  5.05it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 53%|██████████████████████████████████████████████████████▏                                               | 319/600 [01:22<01:07,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 53%|██████████████████████████████████████████████████████▍                                               | 320/600 [01:22<01:04,  4.34it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 54%|██████████████████████████████████████████████████████▌                                               | 321/600 [01:23<01:05,  4.25it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 54%|██████████████████████████████████████████████████████▋                                               | 322/600 [01:24<02:09,  2.14it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 54%|██████████████████████████████████████████████████████▉                                               | 323/600 [01:24<02:02,  2.26it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 54%|███████████████████████████████████████████████████████                                               | 324/600 [01:24<01:40,  2.75it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 54%|███████████████████████████████████████████████████████▏                                              | 325/600 [01:24<01:22,  3.35it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 54%|███████████████████████████████████████████████████████▍                                              | 326/600 [01:25<01:15,  3.64it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 55%|███████████████████████████████████████████████████████▌                                              | 327/600 [01:25<01:15,  3.63it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 55%|███████████████████████████████████████████████████████▊                                              | 328/600 [01:25<01:13,  3.68it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 55%|███████████████████████████████████████████████████████▉                                              | 329/600 [01:25<01:06,  4.07it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 55%|████████████████████████████████████████████████████████                                              | 330/600 [01:25<01:00,  4.45it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 55%|████████████████████████████████████████████████████████▎                                             | 331/600 [01:26<01:00,  4.47it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 55%|████████████████████████████████████████████████████████▍                                             | 332/600 [01:26<01:12,  3.67it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 56%|████████████████████████████████████████████████████████▌                                             | 333/600 [01:26<01:09,  3.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 56%|████████████████████████████████████████████████████████▊                                             | 334/600 [01:27<01:06,  3.98it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 56%|████████████████████████████████████████████████████████▉                                             | 335/600 [01:27<01:04,  4.08it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 56%|█████████████████████████████████████████████████████████                                             | 336/600 [01:27<01:03,  4.15it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 56%|█████████████████████████████████████████████████████████▎                                            | 337/600 [01:28<01:23,  3.14it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 56%|█████████████████████████████████████████████████████████▍                                            | 338/600 [01:28<01:19,  3.30it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 56%|█████████████████████████████████████████████████████████▋                                            | 339/600 [01:28<01:14,  3.48it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 57%|█████████████████████████████████████████████████████████▊                                            | 340/600 [01:28<01:05,  3.94it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 57%|█████████████████████████████████████████████████████████▉                                            | 341/600 [01:28<01:01,  4.23it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 57%|██████████████████████████████████████████████████████████▏                                           | 342/600 [01:29<01:11,  3.62it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 57%|██████████████████████████████████████████████████████████▎                                           | 343/600 [01:29<01:07,  3.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 57%|██████████████████████████████████████████████████████████▍                                           | 344/600 [01:29<01:01,  4.15it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 57%|██████████████████████████████████████████████████████████▋                                           | 345/600 [01:29<00:57,  4.42it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 58%|██████████████████████████████████████████████████████████▊                                           | 346/600 [01:30<00:53,  4.74it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 58%|██████████████████████████████████████████████████████████▉                                           | 347/600 [01:30<00:47,  5.31it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 58%|███████████████████████████████████████████████████████████▏                                          | 348/600 [01:30<00:46,  5.43it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 58%|███████████████████████████████████████████████████████████▎                                          | 349/600 [01:30<00:44,  5.69it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 58%|███████████████████████████████████████████████████████████▌                                          | 350/600 [01:30<00:59,  4.21it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 58%|███████████████████████████████████████████████████████████▋                                          | 351/600 [01:31<01:05,  3.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 59%|███████████████████████████████████████████████████████████▊                                          | 352/600 [01:31<00:58,  4.22it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 59%|████████████████████████████████████████████████████████████                                          | 353/600 [01:31<00:55,  4.45it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 59%|████████████████████████████████████████████████████████████▏                                         | 354/600 [01:31<01:01,  4.03it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 59%|████████████████████████████████████████████████████████████▎                                         | 355/600 [01:32<01:02,  3.94it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 59%|████████████████████████████████████████████████████████████▌                                         | 356/600 [01:32<00:57,  4.23it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 60%|████████████████████████████████████████████████████████████▋                                         | 357/600 [01:32<00:57,  4.23it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 60%|████████████████████████████████████████████████████████████▊                                         | 358/600 [01:32<00:52,  4.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 60%|█████████████████████████████████████████████████████████████                                         | 359/600 [01:32<00:50,  4.82it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 60%|█████████████████████████████████████████████████████████████▏                                        | 360/600 [01:33<00:54,  4.44it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 60%|█████████████████████████████████████████████████████████████▎                                        | 361/600 [01:33<01:14,  3.20it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 60%|█████████████████████████████████████████████████████████████▌                                        | 362/600 [01:33<01:05,  3.63it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 60%|█████████████████████████████████████████████████████████████▋                                        | 363/600 [01:34<01:06,  3.54it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 61%|█████████████████████████████████████████████████████████████▉                                        | 364/600 [01:34<00:58,  4.05it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 61%|██████████████████████████████████████████████████████████████                                        | 365/600 [01:34<00:50,  4.69it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 61%|██████████████████████████████████████████████████████████████▏                                       | 366/600 [01:34<00:49,  4.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 61%|██████████████████████████████████████████████████████████████▍                                       | 367/600 [01:34<00:48,  4.81it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 61%|██████████████████████████████████████████████████████████████▌                                       | 368/600 [01:35<00:43,  5.32it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 62%|██████████████████████████████████████████████████████████████▋                                       | 369/600 [01:35<00:42,  5.42it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 62%|██████████████████████████████████████████████████████████████▉                                       | 370/600 [01:35<00:42,  5.41it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 62%|███████████████████████████████████████████████████████████████                                       | 371/600 [01:35<00:43,  5.27it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 62%|███████████████████████████████████████████████████████████████▏                                      | 372/600 [01:35<00:43,  5.18it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 62%|███████████████████████████████████████████████████████████████▍                                      | 373/600 [01:36<00:46,  4.83it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 62%|███████████████████████████████████████████████████████████████▌                                      | 374/600 [01:36<00:51,  4.41it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 62%|███████████████████████████████████████████████████████████████▊                                      | 375/600 [01:36<00:47,  4.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 63%|███████████████████████████████████████████████████████████████▉                                      | 376/600 [01:36<00:46,  4.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 63%|████████████████████████████████████████████████████████████████                                      | 377/600 [01:36<00:46,  4.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 63%|████████████████████████████████████████████████████████████████▎                                     | 378/600 [01:37<00:44,  4.94it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 63%|████████████████████████████████████████████████████████████████▍                                     | 379/600 [01:37<00:48,  4.51it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 63%|████████████████████████████████████████████████████████████████▌                                     | 380/600 [01:37<00:47,  4.59it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 64%|████████████████████████████████████████████████████████████████▊                                     | 381/600 [01:37<00:49,  4.41it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 64%|████████████████████████████████████████████████████████████████▉                                     | 382/600 [01:38<00:48,  4.52it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 64%|█████████████████████████████████████████████████████████████████                                     | 383/600 [01:38<01:19,  2.72it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 64%|█████████████████████████████████████████████████████████████████▎                                    | 384/600 [01:38<01:06,  3.23it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 64%|█████████████████████████████████████████████████████████████████▍                                    | 385/600 [01:39<00:58,  3.68it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 64%|█████████████████████████████████████████████████████████████████▌                                    | 386/600 [01:39<01:01,  3.46it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 64%|█████████████████████████████████████████████████████████████████▊                                    | 387/600 [01:39<00:58,  3.67it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 65%|█████████████████████████████████████████████████████████████████▉                                    | 388/600 [01:39<00:53,  3.93it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 65%|██████████████████████████████████████████████████████████████████▏                                   | 389/600 [01:40<00:56,  3.73it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 65%|██████████████████████████████████████████████████████████████████▎                                   | 390/600 [01:40<00:52,  4.03it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 65%|██████████████████████████████████████████████████████████████████▍                                   | 391/600 [01:40<00:50,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 65%|██████████████████████████████████████████████████████████████████▋                                   | 392/600 [01:40<00:44,  4.63it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 66%|██████████████████████████████████████████████████████████████████▊                                   | 393/600 [01:40<00:42,  4.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 66%|██████████████████████████████████████████████████████████████████▉                                   | 394/600 [01:41<00:47,  4.30it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 66%|███████████████████████████████████████████████████████████████████▏                                  | 395/600 [01:41<00:45,  4.47it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 66%|███████████████████████████████████████████████████████████████████▎                                  | 396/600 [01:41<00:46,  4.43it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 66%|███████████████████████████████████████████████████████████████████▍                                  | 397/600 [01:41<00:43,  4.67it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 66%|███████████████████████████████████████████████████████████████████▋                                  | 398/600 [01:42<00:42,  4.72it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 66%|███████████████████████████████████████████████████████████████████▊                                  | 399/600 [01:42<01:03,  3.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 67%|████████████████████████████████████████████████████████████████████                                  | 400/600 [01:42<00:54,  3.66it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 67%|████████████████████████████████████████████████████████████████████▏                                 | 401/600 [01:43<00:52,  3.76it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 67%|████████████████████████████████████████████████████████████████████▎                                 | 402/600 [01:43<00:45,  4.34it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 67%|████████████████████████████████████████████████████████████████████▌                                 | 403/600 [01:43<00:39,  5.00it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 67%|████████████████████████████████████████████████████████████████████▋                                 | 404/600 [01:43<00:38,  5.06it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 68%|████████████████████████████████████████████████████████████████████▊                                 | 405/600 [01:43<00:43,  4.51it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 68%|█████████████████████████████████████████████████████████████████████                                 | 406/600 [01:44<00:41,  4.64it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 68%|█████████████████████████████████████████████████████████████████████▏                                | 407/600 [01:44<00:38,  4.99it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 68%|█████████████████████████████████████████████████████████████████████▎                                | 408/600 [01:44<00:41,  4.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 68%|█████████████████████████████████████████████████████████████████████▌                                | 409/600 [01:44<00:45,  4.22it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 68%|█████████████████████████████████████████████████████████████████████▋                                | 410/600 [01:44<00:42,  4.50it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 68%|█████████████████████████████████████████████████████████████████████▊                                | 411/600 [01:45<00:40,  4.61it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 69%|██████████████████████████████████████████████████████████████████████                                | 412/600 [01:45<00:47,  3.93it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 69%|██████████████████████████████████████████████████████████████████████▏                               | 413/600 [01:45<00:43,  4.33it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 69%|██████████████████████████████████████████████████████████████████████▍                               | 414/600 [01:45<00:41,  4.53it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 69%|██████████████████████████████████████████████████████████████████████▌                               | 415/600 [01:46<00:39,  4.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 69%|██████████████████████████████████████████████████████████████████████▋                               | 416/600 [01:46<00:38,  4.77it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 70%|██████████████████████████████████████████████████████████████████████▉                               | 417/600 [01:46<00:32,  5.59it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 70%|███████████████████████████████████████████████████████████████████████                               | 418/600 [01:46<00:33,  5.42it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 70%|███████████████████████████████████████████████████████████████████████▏                              | 419/600 [01:46<00:31,  5.82it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 70%|███████████████████████████████████████████████████████████████████████▍                              | 420/600 [01:47<00:50,  3.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 70%|███████████████████████████████████████████████████████████████████████▌                              | 421/600 [01:47<00:44,  4.05it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 70%|███████████████████████████████████████████████████████████████████████▋                              | 422/600 [01:47<00:45,  3.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 70%|███████████████████████████████████████████████████████████████████████▉                              | 423/600 [01:47<00:41,  4.26it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 71%|████████████████████████████████████████████████████████████████████████                              | 424/600 [01:48<00:38,  4.55it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 71%|████████████████████████████████████████████████████████████████████████▎                             | 425/600 [01:48<00:45,  3.81it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 71%|████████████████████████████████████████████████████████████████████████▍                             | 426/600 [01:48<00:42,  4.11it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 71%|████████████████████████████████████████████████████████████████████████▌                             | 427/600 [01:48<00:39,  4.33it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 71%|████████████████████████████████████████████████████████████████████████▊                             | 428/600 [01:48<00:37,  4.53it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 72%|████████████████████████████████████████████████████████████████████████▉                             | 429/600 [01:49<00:59,  2.86it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 72%|█████████████████████████████████████████████████████████████████████████                             | 430/600 [01:49<00:51,  3.31it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 72%|█████████████████████████████████████████████████████████████████████████▎                            | 431/600 [01:50<00:46,  3.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 72%|█████████████████████████████████████████████████████████████████████████▍                            | 432/600 [01:50<00:41,  4.06it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 72%|█████████████████████████████████████████████████████████████████████████▌                            | 433/600 [01:50<00:42,  3.96it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 72%|█████████████████████████████████████████████████████████████████████████▊                            | 434/600 [01:50<00:36,  4.58it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 72%|█████████████████████████████████████████████████████████████████████████▉                            | 435/600 [01:50<00:40,  4.12it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 73%|██████████████████████████████████████████████████████████████████████████                            | 436/600 [01:51<00:38,  4.29it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 73%|██████████████████████████████████████████████████████████████████████████▎                           | 437/600 [01:51<00:42,  3.87it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 73%|██████████████████████████████████████████████████████████████████████████▍                           | 438/600 [01:51<00:37,  4.33it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 73%|██████████████████████████████████████████████████████████████████████████▋                           | 439/600 [01:52<01:27,  1.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 73%|██████████████████████████████████████████████████████████████████████████▊                           | 440/600 [01:53<01:10,  2.28it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 74%|██████████████████████████████████████████████████████████████████████████▉                           | 441/600 [01:53<00:56,  2.81it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 74%|███████████████████████████████████████████████████████████████████████████▏                          | 442/600 [01:53<00:47,  3.32it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 74%|███████████████████████████████████████████████████████████████████████████▎                          | 443/600 [01:53<00:54,  2.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 74%|███████████████████████████████████████████████████████████████████████████▍                          | 444/600 [01:54<00:46,  3.34it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 74%|███████████████████████████████████████████████████████████████████████████▋                          | 445/600 [01:54<00:39,  3.92it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 74%|███████████████████████████████████████████████████████████████████████████▊                          | 446/600 [01:54<00:50,  3.06it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 74%|███████████████████████████████████████████████████████████████████████████▉                          | 447/600 [01:55<01:11,  2.15it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 75%|████████████████████████████████████████████████████████████████████████████▏                         | 448/600 [01:55<01:01,  2.46it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 75%|████████████████████████████████████████████████████████████████████████████▎                         | 449/600 [01:56<00:55,  2.73it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 75%|████████████████████████████████████████████████████████████████████████████▌                         | 450/600 [01:56<00:47,  3.13it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 75%|████████████████████████████████████████████████████████████████████████████▋                         | 451/600 [01:56<00:59,  2.51it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 75%|████████████████████████████████████████████████████████████████████████████▊                         | 452/600 [01:57<01:00,  2.46it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 76%|█████████████████████████████████████████████████████████████████████████████                         | 453/600 [01:57<00:51,  2.83it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 76%|█████████████████████████████████████████████████████████████████████████████▏                        | 454/600 [01:57<00:56,  2.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 76%|█████████████████████████████████████████████████████████████████████████████▎                        | 455/600 [01:58<00:48,  3.01it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 76%|█████████████████████████████████████████████████████████████████████████████▌                        | 456/600 [01:58<00:42,  3.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 76%|█████████████████████████████████████████████████████████████████████████████▋                        | 457/600 [01:59<01:08,  2.09it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 76%|█████████████████████████████████████████████████████████████████████████████▊                        | 458/600 [01:59<00:56,  2.51it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 76%|██████████████████████████████████████████████████████████████████████████████                        | 459/600 [01:59<00:48,  2.92it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 77%|██████████████████████████████████████████████████████████████████████████████▏                       | 460/600 [01:59<00:41,  3.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 77%|██████████████████████████████████████████████████████████████████████████████▎                       | 461/600 [02:00<00:36,  3.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 77%|██████████████████████████████████████████████████████████████████████████████▌                       | 462/600 [02:00<00:34,  3.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 77%|██████████████████████████████████████████████████████████████████████████████▋                       | 463/600 [02:00<00:39,  3.44it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 77%|██████████████████████████████████████████████████████████████████████████████▉                       | 464/600 [02:00<00:35,  3.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 78%|███████████████████████████████████████████████████████████████████████████████                       | 465/600 [02:01<00:32,  4.19it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 78%|███████████████████████████████████████████████████████████████████████████████▏                      | 466/600 [02:01<00:45,  2.96it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 78%|███████████████████████████████████████████████████████████████████████████████▍                      | 467/600 [02:01<00:41,  3.19it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 78%|███████████████████████████████████████████████████████████████████████████████▌                      | 468/600 [02:02<00:37,  3.50it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 78%|███████████████████████████████████████████████████████████████████████████████▋                      | 469/600 [02:02<00:37,  3.52it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 78%|███████████████████████████████████████████████████████████████████████████████▉                      | 470/600 [02:02<00:34,  3.75it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 78%|████████████████████████████████████████████████████████████████████████████████                      | 471/600 [02:02<00:30,  4.19it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 79%|████████████████████████████████████████████████████████████████████████████████▏                     | 472/600 [02:02<00:28,  4.42it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 79%|████████████████████████████████████████████████████████████████████████████████▍                     | 473/600 [02:04<01:04,  1.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 79%|████████████████████████████████████████████████████████████████████████████████▌                     | 474/600 [02:04<00:51,  2.42it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 79%|████████████████████████████████████████████████████████████████████████████████▊                     | 475/600 [02:04<00:42,  2.94it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 79%|████████████████████████████████████████████████████████████████████████████████▉                     | 476/600 [02:04<00:37,  3.29it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 80%|█████████████████████████████████████████████████████████████████████████████████                     | 477/600 [02:04<00:34,  3.55it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 478/600 [02:05<00:30,  3.97it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 80%|█████████████████████████████████████████████████████████████████████████████████▍                    | 479/600 [02:05<00:27,  4.40it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 80%|█████████████████████████████████████████████████████████████████████████████████▌                    | 480/600 [02:05<00:26,  4.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 80%|█████████████████████████████████████████████████████████████████████████████████▊                    | 481/600 [02:06<00:40,  2.91it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 482/600 [02:06<00:35,  3.30it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 80%|██████████████████████████████████████████████████████████████████████████████████                    | 483/600 [02:06<00:31,  3.69it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 81%|██████████████████████████████████████████████████████████████████████████████████▎                   | 484/600 [02:07<00:50,  2.28it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 81%|██████████████████████████████████████████████████████████████████████████████████▍                   | 485/600 [02:07<00:43,  2.63it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 81%|██████████████████████████████████████████████████████████████████████████████████▌                   | 486/600 [02:07<00:43,  2.65it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 81%|██████████████████████████████████████████████████████████████████████████████████▊                   | 487/600 [02:08<00:37,  3.02it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 81%|██████████████████████████████████████████████████████████████████████████████████▉                   | 488/600 [02:08<00:34,  3.25it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 82%|███████████████████████████████████████████████████████████████████████████████████▏                  | 489/600 [02:08<00:31,  3.58it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 82%|███████████████████████████████████████████████████████████████████████████████████▎                  | 490/600 [02:08<00:28,  3.91it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 82%|███████████████████████████████████████████████████████████████████████████████████▍                  | 491/600 [02:09<00:24,  4.37it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 82%|███████████████████████████████████████████████████████████████████████████████████▋                  | 492/600 [02:09<00:22,  4.71it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 82%|███████████████████████████████████████████████████████████████████████████████████▊                  | 493/600 [02:09<00:23,  4.57it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 82%|███████████████████████████████████████████████████████████████████████████████████▉                  | 494/600 [02:09<00:31,  3.32it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 495/600 [02:10<00:34,  3.01it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 83%|████████████████████████████████████████████████████████████████████████████████████▎                 | 496/600 [02:10<00:29,  3.55it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 497/600 [02:10<00:26,  3.82it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 83%|████████████████████████████████████████████████████████████████████████████████████▋                 | 498/600 [02:10<00:23,  4.33it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 83%|████████████████████████████████████████████████████████████████████████████████████▊                 | 499/600 [02:11<00:29,  3.38it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 83%|█████████████████████████████████████████████████████████████████████████████████████                 | 500/600 [02:11<00:25,  3.91it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 84%|█████████████████████████████████████████████████████████████████████████████████████▏                | 501/600 [02:11<00:27,  3.56it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 502/600 [02:11<00:24,  4.07it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 84%|█████████████████████████████████████████████████████████████████████████████████████▌                | 503/600 [02:12<00:23,  4.20it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 84%|█████████████████████████████████████████████████████████████████████████████████████▋                | 504/600 [02:12<00:24,  3.94it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 84%|█████████████████████████████████████████████████████████████████████████████████████▊                | 505/600 [02:12<00:22,  4.27it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 84%|██████████████████████████████████████████████████████████████████████████████████████                | 506/600 [02:12<00:22,  4.23it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 84%|██████████████████████████████████████████████████████████████████████████████████████▏               | 507/600 [02:13<00:19,  4.69it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 85%|██████████████████████████████████████████████████████████████████████████████████████▎               | 508/600 [02:13<00:19,  4.81it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 85%|██████████████████████████████████████████████████████████████████████████████████████▌               | 509/600 [02:13<00:17,  5.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 85%|██████████████████████████████████████████████████████████████████████████████████████▋               | 510/600 [02:13<00:21,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 85%|██████████████████████████████████████████████████████████████████████████████████████▊               | 511/600 [02:14<00:20,  4.32it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 85%|███████████████████████████████████████████████████████████████████████████████████████               | 512/600 [02:14<00:19,  4.40it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 86%|███████████████████████████████████████████████████████████████████████████████████████▏              | 513/600 [02:14<00:19,  4.37it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 86%|███████████████████████████████████████████████████████████████████████████████████████▍              | 514/600 [02:14<00:19,  4.40it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 515/600 [02:14<00:20,  4.11it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 86%|███████████████████████████████████████████████████████████████████████████████████████▋              | 516/600 [02:15<00:25,  3.34it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 86%|███████████████████████████████████████████████████████████████████████████████████████▉              | 517/600 [02:15<00:21,  3.81it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 86%|████████████████████████████████████████████████████████████████████████████████████████              | 518/600 [02:16<00:25,  3.18it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 86%|████████████████████████████████████████████████████████████████████████████████████████▏             | 519/600 [02:16<00:22,  3.57it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 87%|████████████████████████████████████████████████████████████████████████████████████████▍             | 520/600 [02:16<00:23,  3.46it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 87%|████████████████████████████████████████████████████████████████████████████████████████▌             | 521/600 [02:16<00:20,  3.90it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 87%|████████████████████████████████████████████████████████████████████████████████████████▋             | 522/600 [02:17<00:24,  3.23it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 523/600 [02:17<00:22,  3.41it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 87%|█████████████████████████████████████████████████████████████████████████████████████████             | 524/600 [02:17<00:19,  3.83it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 88%|█████████████████████████████████████████████████████████████████████████████████████████▎            | 525/600 [02:17<00:17,  4.17it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 88%|█████████████████████████████████████████████████████████████████████████████████████████▍            | 526/600 [02:18<00:18,  4.09it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 88%|█████████████████████████████████████████████████████████████████████████████████████████▌            | 527/600 [02:18<00:17,  4.28it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 88%|█████████████████████████████████████████████████████████████████████████████████████████▊            | 528/600 [02:18<00:26,  2.68it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 88%|█████████████████████████████████████████████████████████████████████████████████████████▉            | 529/600 [02:19<00:22,  3.12it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 88%|██████████████████████████████████████████████████████████████████████████████████████████            | 530/600 [02:19<00:19,  3.52it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 88%|██████████████████████████████████████████████████████████████████████████████████████████▎           | 531/600 [02:19<00:17,  3.86it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 89%|██████████████████████████████████████████████████████████████████████████████████████████▍           | 532/600 [02:19<00:16,  4.16it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 89%|██████████████████████████████████████████████████████████████████████████████████████████▌           | 533/600 [02:19<00:15,  4.39it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 89%|██████████████████████████████████████████████████████████████████████████████████████████▊           | 534/600 [02:20<00:14,  4.51it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 89%|██████████████████████████████████████████████████████████████████████████████████████████▉           | 535/600 [02:20<00:15,  4.24it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 89%|███████████████████████████████████████████████████████████████████████████████████████████           | 536/600 [02:20<00:15,  4.24it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 90%|███████████████████████████████████████████████████████████████████████████████████████████▎          | 537/600 [02:20<00:13,  4.60it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 90%|███████████████████████████████████████████████████████████████████████████████████████████▍          | 538/600 [02:21<00:13,  4.64it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 90%|███████████████████████████████████████████████████████████████████████████████████████████▋          | 539/600 [02:21<00:13,  4.68it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 90%|███████████████████████████████████████████████████████████████████████████████████████████▊          | 540/600 [02:21<00:14,  4.07it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 90%|███████████████████████████████████████████████████████████████████████████████████████████▉          | 541/600 [02:21<00:13,  4.52it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 90%|████████████████████████████████████████████████████████████████████████████████████████████▏         | 542/600 [02:21<00:12,  4.49it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 90%|████████████████████████████████████████████████████████████████████████████████████████████▎         | 543/600 [02:22<00:13,  4.29it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 91%|████████████████████████████████████████████████████████████████████████████████████████████▍         | 544/600 [02:22<00:11,  4.88it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 91%|████████████████████████████████████████████████████████████████████████████████████████████▋         | 545/600 [02:22<00:11,  4.87it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 91%|████████████████████████████████████████████████████████████████████████████████████████████▊         | 546/600 [02:22<00:11,  4.87it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 91%|████████████████████████████████████████████████████████████████████████████████████████████▉         | 547/600 [02:22<00:10,  5.10it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 91%|█████████████████████████████████████████████████████████████████████████████████████████████▏        | 548/600 [02:23<00:10,  4.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 92%|█████████████████████████████████████████████████████████████████████████████████████████████▎        | 549/600 [02:23<00:11,  4.53it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 92%|█████████████████████████████████████████████████████████████████████████████████████████████▌        | 550/600 [02:23<00:11,  4.49it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 92%|█████████████████████████████████████████████████████████████████████████████████████████████▋        | 551/600 [02:23<00:12,  3.98it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 92%|█████████████████████████████████████████████████████████████████████████████████████████████▊        | 552/600 [02:24<00:12,  3.72it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 92%|██████████████████████████████████████████████████████████████████████████████████████████████        | 553/600 [02:25<00:19,  2.44it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 92%|██████████████████████████████████████████████████████████████████████████████████████████████▏       | 554/600 [02:25<00:16,  2.76it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 92%|██████████████████████████████████████████████████████████████████████████████████████████████▎       | 555/600 [02:25<00:13,  3.34it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 93%|██████████████████████████████████████████████████████████████████████████████████████████████▌       | 556/600 [02:25<00:11,  3.79it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 93%|██████████████████████████████████████████████████████████████████████████████████████████████▋       | 557/600 [02:25<00:10,  4.05it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 93%|██████████████████████████████████████████████████████████████████████████████████████████████▊       | 558/600 [02:26<00:13,  3.10it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 93%|███████████████████████████████████████████████████████████████████████████████████████████████       | 559/600 [02:26<00:11,  3.46it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 93%|███████████████████████████████████████████████████████████████████████████████████████████████▏      | 560/600 [02:26<00:12,  3.31it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 94%|███████████████████████████████████████████████████████████████████████████████████████████████▎      | 561/600 [02:27<00:10,  3.70it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 94%|███████████████████████████████████████████████████████████████████████████████████████████████▌      | 562/600 [02:27<00:09,  4.21it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 94%|███████████████████████████████████████████████████████████████████████████████████████████████▋      | 563/600 [02:27<00:08,  4.35it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 94%|███████████████████████████████████████████████████████████████████████████████████████████████▉      | 564/600 [02:27<00:07,  4.61it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 94%|████████████████████████████████████████████████████████████████████████████████████████████████      | 565/600 [02:27<00:08,  4.21it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 94%|████████████████████████████████████████████████████████████████████████████████████████████████▏     | 566/600 [02:28<00:08,  4.24it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 94%|████████████████████████████████████████████████████████████████████████████████████████████████▍     | 567/600 [02:28<00:08,  4.01it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 95%|████████████████████████████████████████████████████████████████████████████████████████████████▌     | 568/600 [02:28<00:07,  4.02it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 95%|████████████████████████████████████████████████████████████████████████████████████████████████▋     | 569/600 [02:28<00:07,  4.20it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 95%|████████████████████████████████████████████████████████████████████████████████████████████████▉     | 570/600 [02:29<00:07,  4.11it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████     | 571/600 [02:29<00:06,  4.42it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████▏    | 572/600 [02:29<00:06,  4.53it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████▍    | 573/600 [02:29<00:05,  4.82it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████▌    | 574/600 [02:29<00:05,  4.36it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████▊    | 575/600 [02:30<00:05,  4.47it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████▉    | 576/600 [02:30<00:05,  4.28it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████    | 577/600 [02:31<00:08,  2.68it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████▎   | 578/600 [02:31<00:07,  3.13it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████▍   | 579/600 [02:31<00:05,  3.56it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████▌   | 580/600 [02:32<00:08,  2.41it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████▊   | 581/600 [02:32<00:08,  2.25it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████▉   | 582/600 [02:32<00:06,  2.73it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████   | 583/600 [02:33<00:05,  3.10it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████▎  | 584/600 [02:33<00:04,  3.42it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████▍  | 585/600 [02:33<00:03,  3.84it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████▌  | 586/600 [02:33<00:03,  4.14it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████▊  | 587/600 [02:34<00:03,  3.91it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████▉  | 588/600 [02:34<00:02,  4.23it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 589/600 [02:34<00:02,  4.22it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 590/600 [02:34<00:02,  4.72it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 591/600 [02:34<00:01,  4.50it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 99%|████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 592/600 [02:35<00:01,  4.51it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 99%|████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 593/600 [02:35<00:01,  4.49it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 99%|████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 594/600 [02:35<00:01,  4.20it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏| 595/600 [02:35<00:01,  4.40it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎| 596/600 [02:36<00:01,  3.63it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍| 597/600 [02:36<00:00,  3.43it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋| 598/600 [02:36<00:00,  3.69it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊| 599/600 [02:37<00:00,  3.63it/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.…

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [02:37<00:00,  3.81it/s]

Done for 157.68 seconds

In [13]:
#saving the baseline results

res_path = "./test.json"
results.save(res, res_path)

In [14]:
demo_public_id = 0
print(questions_ds["train"].filter(lambda it: it["id"] == demo_public_id)[0])
print('\n' + json.dumps(res[demo_public_id], ensure_ascii=False, indent=4))

{'id': 0, 'question': 'Каково атмосферное давление в Москве?'}

{
    "found_ids": [
        156,
        63,
        16,
        47,
        2
    ],
    "model_answer": "747 миллиметров ртутного столба"
}

In [15]:
#calculate metrics

evaluation_results = evaluator.evaluate_rag_results(res, qa_dataset, mapping)

In [16]:
#average metrics

res_agg = evaluation_results.average_metrics

df_retrieval = pd.DataFrame([res_agg["retrieval"]], index=["retrieval"]).apply(pd.to_numeric, errors="coerce")
df_generation = pd.DataFrame([res_agg["generation"]], index=["generation"]).apply(pd.to_numeric, errors="coerce")

df_retrieval = df_retrieval.round(4)
df_generation = df_generation.round(4)

In [17]:
df_retrieval

           hit_rate     mrr
retrieval    0.8112  0.8037

In [18]:
df_generation

            rouge1  rouge2  rougeL      em  substring_match
generation  0.4967  0.3092   0.476  0.2133            0.255